server:
  port: 10022

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: org.vico.restful.pojo

spring:
  application:
    name: vico-restful-server
  redis:
    max-redirects: 3
    database: 1
    port: 6379
    host: 47.111.136.145
    password: 7XQnwjQvvaXWbjYYhaKy
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.111.136.145:3306/vico?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 3295286
  rabbitmq:
    host: 47.111.136.145
    port: 5672
    username: mquser
    password: 3295286

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/


auth:
  server-meta:
    prefix: IM_SERVER_META#
  exchange: IM_MSG_EXCHANGE
  queue: 127.0.0.1#10002