server:
  port: 10021

mybatis:
  type-aliases-package: org.vico.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  application:
    name: vico-auth-server
  redis:
    cluster:
      nodes: 47.93.97.143:6379,8.131.63.174:6379,121.196.145.204:6379
    sentinel:
      master: mymaster
      nodes: 47.93.97.143:26379,8.131.63.174:26379,121.196.145.204:26379
    max-redirects: 3
    database: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.97.143:3306/vico?useUnicode=true&characterEncoding=utf-8
    username: root
    password: rootpassword

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

auth:
  secret: Zxc3295.@0